# Spring Configuration
spring:
  application:
    name: openapi-demo
  profiles:
    active: dev

# MyBatis Configuration
mybatis:
  configuration:
    cache-enabled: false
    jdbc-type-for-null: varchar
